davidhu2000/react-spinners

package.json
As mentioned in #9 , there is a dependency error that stop all spinners from working.
=> recompose should be dependency, not devDependency

src/spinners/PulseLoader.jsx
size should be number, not string
=> Fix prop type mismatch

package.json, yarn.lock
=> moved emotion from devDependency to dependency

package.json, src/index.d.ts
Hi! Nice project. :) I added typescript definitions in this commit, so react-spinners npm package could be used in typescipt projects. First I wanted to publish them in DefinitelyTyped repo, but then I decided it would be better if they were part of the project itself.
=> Added typescript definitions

src/spinners/RingLoader.jsx
correct borderRadius to border-radius so browsers will recognize.
=> correct borderRadius to border-radius so browsers will recognize.

src/spinners/ScaleLoader.jsx
=> Add missing px in border radius

README.md
=> update README table

__tests__/ClipLoader-tests.tsx, __tests__/DotLoader-tests.tsx, __tests__/FadeLoader-tests.tsx, __tests__/GridLoader-tests.tsx, __tests__/HashLoader-tests.tsx, __tests__/MoonLoader-tests.tsx, __tests__/__snapshots__/ClipLoader-tests.tsx.snap, __tests__/__snapshots__/DotLoader-tests.tsx.snap, __tests__/__snapshots__/FadeLoader-tests.tsx.snap, __tests__/__snapshots__/GridLoader-tests.tsx.snap, __tests__/__snapshots__/HashLoader-tests.tsx.snap, __tests__/__snapshots__/MoonLoader-tests.tsx.snap
Add testing for 
- cliploader
- dot loader
- fade loader
- gridloader
- hashloader
- moonloader
=> Testing for 6 additional loaders

__tests__/BarLoader-tests.tsx, __tests__/BeatLoader-tests.tsx, __tests__/BounceLoader-tests.tsx
refactored BarLoader, BeatLoader, and BounceLoader tests to use default variables.
=> Refactor Bar/Beat/Bounce loader tests to use default variables

__tests__/DotLoader-tests.tsx, __tests__/FadeLoader-tests.tsx, __tests__/GridLoader-tests.tsx, __tests__/__snapshots__/GridLoader-tests.tsx.snap, src/GridLoader.tsx
=> Update dot/fade/grid loader tests to use default variables

__tests__/HashLoader-tests.tsx, __tests__/MoonLoader-tests.tsx
=> Update hash/moon loader tests to use default variables

__tests__/PacmanLoader-tests.tsx, __tests__/PropagateLoader-tests.tsx, __tests__/PulseLoader-test.tsx
=> Update pacman/propagate/pulse loader tests

__tests__/RingLoader-tests.tsx, __tests__/RiseLoader-tests.tsx, __tests__/RotateLoader-tests.tsx
=> Update tests for ring/rise/rotate loaders

__tests__/ScaleLoader-tests.tsx, __tests__/SkewLoader-tests.tsx, __tests__/SquareLoader-tests.tsx, __tests__/SyncLoader-tests.tsx
=> Update scale/skew/square/sync loader tests to use defaultUnit variable

CHANGELOG.md, README.md, package.json
=> update readme to include list of colors and update default css value

src/index.ts
=> use tree shaking

src/BarLoader.tsx, src/BeatLoader.tsx, src/BounceLoader.tsx, src/CircleLoader.tsx, src/ClimbingBoxLoader.tsx, src/ClipLoader.tsx, src/ClockLoader.tsx, src/DotLoader.tsx, src/FadeLoader.tsx, src/GridLoader.tsx, src/MoonLoader.tsx, src/PacmanLoader.tsx, src/PropagateLoader.tsx, src/PuffLoader.tsx, src/PulseLoader.tsx, src/RingLoader.tsx, src/RiseLoader.tsx, src/RotateLoader.tsx, src/ScaleLoader.tsx, src/SkewLoader.tsx, src/SquareLoader.tsx, src/SyncLoader.tsx
=> Remove Keyframes type to allow for inferring

README.md
=> Update readme with react hooks. Hide class example using details

__tests__/__snapshots__/MoonLoader-tests.tsx.snap, src/MoonLoader.tsx
=> Fix MoonLoader animation

__tests__/BarLoader-tests.tsx, __tests__/sharedSpecs/speedMultiplerSpecs.tsx
=> Refactor speedMultiplierSpecs into common spec

__tests__/BarLoader-tests.tsx, __tests__/PulseLoader-test.tsx, __tests__/__snapshots__/PulseLoader-test.tsx.snap, src/PulseLoader.tsx
=> Pulseloader speed multiplier

__tests__/BarLoader-tests.tsx, __tests__/BeatLoader-tests.tsx, __tests__/BounceLoader-tests.tsx, __tests__/PulseLoader-test.tsx, __tests__/__snapshots__/BarLoader-tests.tsx.snap, __tests__/__snapshots__/BeatLoader-tests.tsx.snap, __tests__/__snapshots__/BounceLoader-tests.tsx.snap, __tests__/__snapshots__/PulseLoader-test.tsx.snap, __tests__/sharedSpecs/commonSpecs.tsx, __tests__/sharedSpecs/cssSpecs.tsx, __tests__/sharedSpecs/index.ts, __tests__/sharedSpecs/speedMultiplierSpecs.tsx
=> create css prop shared specs

__tests__/BarLoader-tests.tsx, __tests__/sharedSpecs/index.ts, __tests__/sharedSpecs/lengthSpecs.tsx
=> create shared length spec

src/BeatLoader.tsx, src/BounceLoader.tsx, src/CircleLoader.tsx, src/ClimbingBoxLoader.tsx, src/ClipLoader.tsx, src/DotLoader.tsx, src/FadeLoader.tsx, src/GridLoader.tsx, src/HashLoader.tsx, src/MoonLoader.tsx, src/PacmanLoader.tsx, src/PropagateLoader.tsx, src/PuffLoader.tsx, src/PulseLoader.tsx, src/RingLoader.tsx, src/helpers/animation.test.ts, src/helpers/animation.ts
Updated animation name to be always unique, so updated animation function to require a suiffix.
=> Add suffix to all animations to avoid potential conflicts

.github/workflows/tests.yml
=> Fix demo site workflow to error on changes

examples/index.tsx, src/GridLoader.tsx, src/PacmanLoader.tsx, src/PuffLoader.tsx
=> Format styles

.babelrc, .eslintrc.js, jest.config.js, package.json, yarn.lock
=> remove emotion as a dependency

.github/workflows/tests.yml
=> update tests workflow to only run on PRs

src/BounceLoader.tsx, src/CircleLoader.tsx, src/FadeLoader.tsx, src/GridLoader.tsx, src/HashLoader.tsx, src/PulseLoader.tsx, src/RiseLoader.tsx
- fix animations, need `;` instead of `,`
- fix default size on bounce and circle loader
- feature: update riseLoader raise amount to be the same as size variable
=> Fix loader animations 

src/BeatLoader.tsx, src/BounceLoader.tsx, src/CircleLoader.tsx, src/ClimbingBoxLoader.tsx, src/ClipLoader.tsx, src/ClockLoader.tsx, src/DotLoader.tsx, src/FadeLoader.tsx, src/GridLoader.tsx, src/HashLoader.tsx, src/MoonLoader.tsx, src/PacmanLoader.tsx, src/PropagateLoader.tsx, src/PuffLoader.tsx, src/PulseLoader.tsx, src/RingLoader.tsx, src/RiseLoader.tsx, src/RotateLoader.tsx, src/ScaleLoader.tsx, src/SyncLoader.tsx
=> add default display inherit

CHANGELOG.md, package.json
=> Add changelog and bump version to 0.13.0-alpha.4

yarn.lock
=> update all dependencies

README.md, package.json
add some more read me badges. merge npm tags alpha/beta into next
=> Add some more readme badges

CHANGELOG.md, package.json
updating documentation for 0.13.0 release.
=> 0.13-release

.github/workflows/deploy.yml, .github/workflows/github-pages.yml
=> create github action to deploy demo/storybook instead of manual builds

.storybook/preview.js, package.json
using the https://github.com/hipstersmoothie/storybook-dark-mode/issues/180#issuecomment-1140553924 to fix darkmode in docs mode.
=> fix darkmode on storybook

src/MoonLoader.tsx
=> fix: moon loader wobble

.github/workflows/deploy.yml, .gitignore, src/helpers/animation.server.test.ts, src/helpers/animation.test.ts, src/helpers/animation.ts
Reverts davidhu2000/react-spinners#602
there are multiple issues with this, also see #604 
reverting to publish a patch
=> Revert "fix: multiple hash loader with different color renders as the same color"

.github/dependabot.yml
=> chore: add-dependabot-gruping

examples/index.html, examples/styles.css
=> chore: cleanup demo page, add more seo

.gitignore, package.json
=> release 0.17.0-beta.1

.npmignore
=> chore: add eslint config to npmignore

package.json
=> chore: release-0.17.0

examples/styles.css, package.json
removed unnecessary padding that make mobile look weird
=> demo: fix mobile styling
