davidhu2000/react-spinners

- src/index.d.ts
- src/spinners/BarLoader.jsx
- src/spinners/BeatLoader.jsx
- src/spinners/BounceLoader.jsx
- src/spinners/CircleLoader.jsx
- src/spinners/ClimbingBoxLoader.jsx
- src/spinners/ClipLoader.jsx
- src/spinners/DotLoader.jsx
- src/spinners/FadeLoader.jsx
- src/spinners/GridLoader.jsx
- src/spinners/HashLoader.jsx
- src/spinners/MoonLoader.jsx
- src/spinners/PacmanLoader.jsx
- src/spinners/PropagateLoader.jsx
- src/spinners/PulseLoader.jsx
- src/spinners/RingLoader.jsx
- src/spinners/RiseLoader.jsx
- src/spinners/RotateLoader.jsx
- src/spinners/ScaleLoader.jsx
- src/spinners/SkewLoader.jsx
- src/spinners/SquareLoader.jsx
- src/spinners/SyncLoader.jsx
This fixes issue #27 by allowing the option to overwrite the default px unit value with another string unit.
> Adds new Unit prop for width, length, and size.

- README.md
- src/helpers/index.js
- src/spinners/BarLoader.jsx
- src/spinners/BeatLoader.jsx
- src/spinners/BounceLoader.jsx
- src/spinners/CircleLoader.jsx
- src/spinners/ClimbingBoxLoader.jsx
- src/spinners/ClipLoader.jsx
- src/spinners/DotLoader.jsx
- src/spinners/FadeLoader.jsx
- src/spinners/GridLoader.jsx
- src/spinners/HashLoader.jsx
- src/spinners/MoonLoader.jsx
- src/spinners/PacmanLoader.jsx
- src/spinners/PropagateLoader.jsx
- src/spinners/PulseLoader.jsx
- src/spinners/RingLoader.jsx
- src/spinners/RiseLoader.jsx
- src/spinners/RotateLoader.jsx
- src/spinners/ScaleLoader.jsx
- src/spinners/SkewLoader.jsx
- src/spinners/SquareLoader.jsx
- src/spinners/SyncLoader.jsx
This is a preliminary proposal to allow for inner styling on the loaders.
This resolves Issue #2 Issue #29? , and is a successor to PR #3 
Please make any recommendations, and once agreed upon, I will apply this for the rest of the loaders.
CX is used so that users can set their positioning without affecting the default props,
> Adds loaderStyle prop to allow for inner styling

- CONTRIBUTING.md
- README.md
The Clip Loader example had the wrong prop types:
`Warning: Failed prop type: Invalid prop 'size' of type 'string' supplied to 'Loader', expected 'number'.`
Also, the CONTRIBUTING docs were missing `run` or `run-script` for the prepublish step, so I added that.
> fix Readme example and CONTRIBUTING prepublish

- src/BarLoader.jsx
- src/BeatLoader.jsx
- src/BounceLoader.jsx
- src/CircleLoader.jsx
- src/ClimbingBoxLoader.jsx
- src/ClipLoader.jsx
- src/DotLoader.jsx
- src/FadeLoader.jsx
- src/GridLoader.jsx
- src/HashLoader.jsx
- src/MoonLoader.jsx
- src/PacmanLoader.jsx
- src/PropagateLoader.jsx
- src/PulseLoader.jsx
- src/RingLoader.jsx
- src/RiseLoader.jsx
- src/RotateLoader.jsx
- src/ScaleLoader.jsx
- src/SkewLoader.jsx
- src/SquareLoader.jsx
- src/SyncLoader.jsx
- Since this comes from a fork, I guess it is ok to work in my master branch :P 
2. run `npm run test` and ensure that all tests pass:
- Tests are passing.
- Okidoki, there you go!
- I basically removed unnecessary imports for the generic recompose package. Currently importing `react-spinners` means also adding an extra recompose bundle of 12kb, even thou you're already using it in the project. This makes it more specific and more proper for tree-shaking.
- There is no issue …
> build: removes unnecessary generic import for recompose utility

- package-lock.json
- package.json
A project I am working on uses both react-spinners and recompose, and currently we're either locked to using the version that react-spinners requires, or duplicate the recompose code in our bundle. Looking at the library's usage, I cannot find any reason react-spinner is locked to the recompose version (the `onlyUpdateForKeys` function that it uses has not changed in 2 years, and the functions that `onlyUpdateForKeys` depends appear to have been stable for a long time, too).
After making the change I ran the demo page locally and it looks to be functioning correctly to me with no errors in the console.
Note: Recompose is no longer going to receive feature updates, so it likely will never see a version past 0.30.0.
> Allow a wider range of Recompose versions

- README.md
No functionality changes, but fixes missing closing quote in .babelrc config from README.
> Add missing closing quote in sample .babelrc config in the README file.

- package.json
While looking in the [Codesandbox compatibility issue](https://github.com/davidhu2000/react-spinners/issues/56) I realized that the package.json file specified `"main": "dist/index.js"` even though this dist folder is not created during prepare (built files are rather put at the root).
This PR just updates the main to point to the right file.
This should also fix the codesandbox issue as it will now know where the built files are.
> Fix main path in package.json

- CHANGELOG.md
- package.json
- updated changelog for `0.6.0`
- bump `package.json` version
> Prepping for v0.6.0 release (TypeScript rewrite)

- __tests__/helpers/unitConverter-tests.ts
- src/helpers/index.ts
- src/helpers/unitConverter.ts
- src/interfaces.ts
Adding a function to convert the size prop to the appropriate string. 
if number => number+px
if string => validate unit, if valid, return as is, else default to px with console warning
> [Unit Prop Removal] add unit converter function and tests

- __tests__/BarLoader-tests.tsx
- __tests__/BeatLoader-tests.tsx
- __tests__/BounceLoader-tests.tsx
- __tests__/__snapshots__/BarLoader-tests.tsx.snap
- __tests__/__snapshots__/BeatLoader-tests.tsx.snap
- __tests__/__snapshots__/BounceLoader-tests.tsx.snap
- __tests__/helpers/proptypes-tests.ts
- __tests__/helpers/unitConverter-tests.ts
- docs/index.html
- examples/index.tsx
- src/BarLoader.tsx
- src/BeatLoader.tsx
- src/BounceLoader.tsx
- src/helpers/proptypes.ts
- src/helpers/unitConverter.ts
- src/interfaces.ts
- tslint.json
- removed sizeUnit, heightUnit, widthUnit, and radiusUnit from proptypes and interfaces. 
- updated BounceLoader/BarLoader/BeatLoader to remove the unit prop.
- changed `css` prop default to `""` to fix typescript error for `{}` is not `PrecompiledCss`
Tests should continue to fail until all the loaders have the correct props
> unit props deprecation: update proptypes and interfaces + bounceloader

- __tests__/BarLoader-tests.tsx
- __tests__/BeatLoader-tests.tsx
- __tests__/BounceLoader-tests.tsx
- __tests__/__snapshots__/BarLoader-tests.tsx.snap
- __tests__/__snapshots__/BeatLoader-tests.tsx.snap
- __tests__/__snapshots__/BounceLoader-tests.tsx.snap
- __tests__/helpers/proptypes-tests.ts
- __tests__/helpers/unitConverter-tests.ts
- docs/index.html
- examples/index.tsx
- src/BarLoader.tsx
- src/BeatLoader.tsx
- src/BounceLoader.tsx
- src/helpers/proptypes.ts
- src/helpers/unitConverter.ts
- src/interfaces.ts
- tslint.json
Reverts davidhu2000/react-spinners#136
temporaily reverting to fix demo site
> Revert "unit props deprecation: update proptypes and interfaces + bounceloader"

- src/MoonLoader.tsx
Recent versions of Tailwind CSS force everything to `box-sizing: border-box;`
(see https://github.com/tailwindcss/tailwindcss/pull/1111 )
Tailwind isn't the only thing out there using that hack, so this is sure to be a wider-ranging problem.
The result of using Tailwind & react-spinners in the same project without this change is that the spinner circle wobbles around.
> Make the box-sizing explicit on the MoonLoader circle

- README.md
- __tests__/PuffLoader-tests.tsx
- src/PuffLoader.tsx
- src/index.ts
Have added a new Puff Loader with a respective test file. The puff loader is taken from [http://samherbert.net/svg-loaders/](http://samherbert.net/svg-loaders/)(2nd row, 4th column http://samherbert.net/svg-loaders/svg-loaders/puff.svg) referenced in the feature request #43 . Please review and suggest any changes.
Thank you.
> New Puff Loader with tests

- CHANGELOG.md
- tsconfig.build.json
the compiler option was not overriding properly, so the outputted files are es2015 (with `import` syntax) vs commonjs (with `require` syntax. This could cause similar issues like #74. 
Now the tsconfig module field will properly override during build phase.
> Properly override module in tsconfig build

- __tests__/BarLoader-tests.tsx
- __tests__/BeatLoader-tests.tsx
- __tests__/BounceLoader-tests.tsx
- __tests__/PulseLoader-test.tsx
- __tests__/sharedSpecs/commonSpecs.tsx
- jest.config.js
- prettier.config.js
```
it("should match snapshot", () => {
it("should contain default props if no props are passed", () => {
it("should render null if loading prop is set as false", () => {
```
these 4 tests are now moved to a commonSpec file and runs for all loaders
> Refactor common specs to a helper

- .github/workflows/tests.yml
While the package is in beta or alpha, the demo site action shouldn't fail since we don't want to update the site code
> demo site action do not fail on alpha / beta verions

- CHANGELOG.md
- package.json
- src/GridLoader.tsx
an attempt to resolve #386. thinking is the width is overwritten somehow causing the grid to not render properly
as a test, we can try to overwrite the width this way.
```
<GridLoader css={{ width: 300 }} />
```
This fix won't prevent the above from happening, but should prevent overrides from outside css.
> Add important to width and height to prevent overwrite

- CHANGELOG.md
- package.json
- src/GridLoader.tsx
the important tag is assigned to the wrong height width. it should be on the outside `span`. Also, inline important tag doesn't work, so used ref instead
> Fix GridLoader not showing issue, bump to bump

- src/CircleLoader.tsx
Animation fill mode property removed. I am using next, and it is throwing errors, as the server side does not load empty CSS properties.
> Remove Animation Fill Mode

- scripts/stories.rb
> docs: fix radius prop type in storybook to be number instead of object

- examples/index.tsx
- scripts/mod.rb
- src/BarLoader.tsx
- src/BeatLoader.tsx
- src/BounceLoader.tsx
- src/CircleLoader.tsx
- src/ClimbingBoxLoader.tsx
- src/ClipLoader.tsx
- src/ClockLoader.tsx
- src/DotLoader.tsx
- src/FadeLoader.tsx
- src/GridLoader.tsx
- src/HashLoader.tsx
- src/MoonLoader.tsx
- src/PacmanLoader.tsx
- src/PropagateLoader.tsx
- src/PuffLoader.tsx
- src/PulseLoader.tsx
- src/RingLoader.tsx
- src/RiseLoader.tsx
- src/RotateLoader.tsx
- src/ScaleLoader.tsx
- src/SkewLoader.tsx
- src/SquareLoader.tsx
- src/SyncLoader.tsx
return type isn't necessary, so we can remove it to keep things simple
> chore: remove-jsx-element return type

- examples/components/ColorPicker.tsx
- examples/index.tsx
- examples/styles.css
- package.json
- yarn.lock
updated dependencies caused page to crash if color picker is clicked
> chore: fix-color-picker throw exception 

- CHANGELOG.md
> chore deprecate-changelog in favor of github releases

- src/ScaleLoader.tsx
to fix https://github.com/davidhu2000/react-spinners/pull/617#discussion_r2042941858
the prop should not be required
> fix: update scale loader prop to be optional to fix breaking change

- .npmignore
| file | size|
|-|-|
CHANGELOG.md | 22.4 kB
.yarnrc.yml | 185 B
.prettierrc.cjs | 185 B
tests/* | 1.07 kB
scripts/* |  3.5 kB
.vscode/* | 130 B
this is ~27.5kb saved per download. 
this roughly saves to 13.5GB/week or 700GB/year of bandwidth
> chore: add unnecessary files to npmignore 

- package.json
- tsconfig.umd.json
umd isn't really useful for this package, as it can't run via a script tag 
```html
<script src="https://unpkg.com/react-spinners@latest/umd/react-spinners.min.js"></script>
```
due to the dependency on react. The `umd` folder is also `149 kB`, which is about 73.5GB of bandwidth a week, or 3.8TB a year.
also, searched for `https://unpkg.com/react-spinners` on google and github, didn't find anything, so we should be ok
> chore: remove umd files from npm publish

- package.json
- tsconfig.json
#647 didn't work, we can no longer import via path, so we need the files in the root directory. 
checking on pkg-size, looks like it break a few things
https://pkg-size.dev/react-spinners@0.17.0-beta.4
> chore: revert cjs changes, remove `cjs` folder from build outputs

- README.md
the original version was added before tree shaking worked on this package, now that it works, we don't need to recommend this old way of importing.
> chore: update readme example to not use path import
